### ISSUE TITLE
Download Creation

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [WhiteAbeLincoln/PTO_Angular#2]
Download files aren't saved on the server unless a specific directory structure already exists (PTO_Angular/files/downloads).

Add some error checking code that creates these folders if they do not already exist, before the attempt is made to save the file on the server.

**Comment by chudiarchimalo** [comment]
?

Sent from my Sprint Samsung Galaxy S® 6.-------- Original message --------

**Comment by WhiteAbeLincoln** [comment]
You don't have to worry about it. I was just making a note so I can
remember to fix it when I have time.

**Comment by WhiteAbeLincoln** [comment]
Fixed a long time ago.
